server:
  port: 8084

spring: 
  application:
    name: note-service
    
  config:
    activate:
      on-profile: local
microservice:
  patient-service-url: ${PATIENT_SERVICE_URL:http://localhost:8080/patients}
  note-service-url: ${NOTE_SERVICE_URL:http://localhost:8083/notes}
 
