server:
  port: 8084

spring: 
  application:
    name: note-service
    
  config:
    activate:
      on-profile: docker
      
microservice:
  patient-service-url: ${PATIENT_SERVICE_URL:http://patient-service:8080/patients}
  note-service-url: ${NOTE_SERVICE_URL:http://note-service:8083/notes}
 
